
mybatis:
  mapper-locations: classpath:resources/mapper/*.xml
  config-location: classpath:mapper/mapper-config.xml

server:
  port: 443
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:server.jks
    key-store-type: PKCS12
    key-store-password: 1q2w3e4r!
    enabled-protocols: TLSv1.2,TLSv1.3
spring:
  profiles:
    include: api-db